### ISSUE TITLE
log-input

### ISSUE THREAD

**Issue by MerleMak** [MerleMak/capstone-project#2]
## Value Proposition

**As a** sailor
**I want** to enter data about my sailing trip 
**so that** it can be used later 

## Description

<img src="https://user-images.githubusercontent.com/98704849/159737467-83f0396f-f2e9-4f6e-a6e9-891ace1dad0e.png" alt="wireframe for log-input" width="300"/>

## Acceptance Criteria

- [x] the form submits, when button "save" is clicked"
- [x] the input is required to submit the form
- [x] when the form submits the input is set to default.

## Tasks

- [x] create a branch "log-form"
- [x] create "form" component
- [x] add specs and storybook for "form" component
- [x] create "input" component
- [x] add specs and storybook for "input" component
- [x] add input component with "Notes" to form
- [x] create component "button"
- [x] add specs and storybook for "button" component
- [x] add form with input and button to "App.js"
- [x] create and style "h1" with name of the app as header and add to App.js

**Comment by MerleMak** [comment]
## Value Proposition

**As a** sailor
**I want** to enter data about my sailing trip 
**so that** it can be used later 


## Description

<img src="https://user-images.githubusercontent.com/98704849/159737467-83f0396f-f2e9-4f6e-a6e9-891ace1dad0e.png" alt="wireframe for log-input" width="300"/>


## Acceptance Criteria

- [ ] the form submits, when button "save" is clicked"
- [ ] the input is required to submit the form
- [ ] when the form submits the input is set to default.


## Tasks

- [ ] create a branch "log-input"
- [ ] create form component
- [ ] add specs and storybook for "form" component
- [ ] add input "Notes" to form
- [ ] create component "button"
- [ ] add specs and storybook for "button" component
