### ISSUE TITLE
log-form-1

### ISSUE THREAD

**Issue by MerleMak** [MerleMak/capstone-project#3]
## Value Proposition
**As a** user
**I want to** enter specific data to a log entry 
**so that** legal requirements can be satisfied

## Description

<img src="https://user-images.githubusercontent.com/98704849/159949001-8a36cf26-6750-4283-b6c8-9a73be1b3cf8.png" width="300"/>

## Acceptance Criteria

- [x] Inputs "name of the boat" has a max input of 40 characters
- [x] Input "names of the crew" has a max input of 250 characters
- [x] Input "wind force" gets a numeric input between 0 and 80
- [x] Input "wind direction" has a max input of 4 characters
- [x] Input "wave size" gets a numeric input between 0 and 20
- [x] Input "notes" has a max input of 500 characters
- [x] the inputs "name of the boat", "wind force", "wind direction" and "wave size" are required

## Tasks

- [x] add 6 "input" component to "form" with labels
- [x] add css grid
- [x] create logic to save input values in useState
- [x] test on supported browsers and different devices
