### ISSUE TITLE
log-history

### ISSUE THREAD

**Issue by MerleMak** [MerleMak/capstone-project#4]
## Value Proposition

**As a** user
**I want** to have a history of log entries
**so that** I can review my sailing trip

## Description

<img src="https://user-images.githubusercontent.com/98704849/159990921-34808e88-6caa-4c11-9bac-19e04de730e8.png" alt="log-form w/history" width="300">

## Acceptance Criteria

- [x] on click of the button "go to log", the history page appears
- [x] the data appears on a card 
- [x] if one or more inputs are left empty, they are not displayed in the card. 
- [x] none of the fields are required
- [x] a button "create new log entry" returns display to empty form
- [x] if no entries are saved and User clicks on "go to log" the empty state is displayed

## Tasks

- [x] create branch "log-entry"
- [x] create card component with the input values of form
- [x] add specs and stories and styled components to card component
- [x] Add button component with "go to log" to form
- [x] update specs of log-form
- [x] create history page and link to form with useNavigate
- [x] add ternary operator logic to display card(s) or empty state
- [x] add button component with "create new log entry" to history page
- [x] add specs for buttons with useNavigate
