### ISSUE TITLE
local-storage 

### ISSUE THREAD

**Issue by MerleMak** [MerleMak/capstone-project#5]
## Value Proposition

**As a** user
**I want** for my data in the logbook to persist 
**so that** I can still refer to it after i closed the app

## Description

Add local storage to save the logbook data when the app is refreshed or reopened after closing

## Acceptance Criteria

- [x] when the page is refreshed the cards are still visible
- [x] new log-entry-card are added to the top of the history page 

## Tasks

- [x] Create branch "local-storage"
- [x] Create local storage logic with useState
- [x] test on all supported browsers and different devices
