### ISSUE TITLE
delete-cards 

### ISSUE THREAD

**Issue by MerleMak** [MerleMak/capstone-project#8]
## Value Proposition

**As a** user
**I want** to delete cards
**so that** I can get rid of cards that are not relevant or contain false data

## Description

<img src="https://user-images.githubusercontent.com/98704849/160254897-485df555-abff-4e59-bd4a-d345ae8aa4f5.png" alt="delete-entry-log" width="300">

## Acceptance Criteria

- [x] when clicking on the "delete" icon, a warning appears that ask the user, if they really want to delete the card. 
- [x] when clicking "yes, delete card", the card disappears
- [x] when clicking "cancel" the warning disappears and the user returns back to history page, like it was.
- [x] when all cards are deleted, the history page shows the empty state

## Tasks

- [x] add "delete" icon to card component
- [x] add delete logic to App
- [x] update specs of card component
