### ISSUE TITLE
image-upload

### ISSUE THREAD

**Issue by MerleMak** [MerleMak/capstone-project#9]
## Value Proposition

**As a** user
**I want** to upload pictures to my log entries
**so that** I can visualise and remember different days/entries better

## Description

<img src="https://user-images.githubusercontent.com/98704849/160351203-fd8c0943-c90d-4d47-b03c-74c695ed0794.png" alt="image-upload" width="300"/>

## Acceptance Criteria

- [x] when clicked on the upload field, the Gallery/ Images folder is opened
- [x] when one image is chosen from the gallery, the display returns to the form in the app
- [x] when the image is uploaded into the app it appears in the a small format in the app
- [x] when the form is saved with an uploaded image, the image appears on last position of the card 
- [x] when the image is horizontal, it is displayed as horizontal over the full width of the card 
- [x] when the image is vertical, it is displayed as vertical over the same pixel length as a horizontal picture with the according width 

## Tasks

- [x] research on cloudinary
- [x] implementation of cloudinary
- [x] add upload field to form component
- [x] update form specs and story
- [x] add image to card component
- [x] set display size of image in card
